[package]
name = "codebook-zed"
version = "0.1.0"
edition = "2021"
authors = ["Bo"]
description = "Codebook: A Zed extension for spellchecking."

[dependencies]
zed_extension_api = "<1"


[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
