[package]
name = "codebook-zed"
version = "0.1.0"
edition = "2021"
authors = ["Bo"]
description = "Codebook: A Zed extension for spellchecking."

[dependencies]
zed_extension_api = "<1"


[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
lto = true # Enables link-time-optimizations.
opt-level = "s" # Prioritizes small binary size. Use `3` if you prefer speed.
strip = true # Ensures debug symbols are removed.

